services:
  parallai.host:
    image: ghcr.io/feytox/parallai:latest
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - MONGO_CONNECTION_STRING=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo-db:27017/ParallAIDB?authSource=admin
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: